# Generated by Django 3.2.6 on 2021-08-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lugar', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=64)),
                ('id_conferencista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.conferencista')),
            ],
        ),
    ]
