# Generated by Django 3.2.3 on 2021-08-27 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencia',
            old_name='link',
            new_name='zoom_id',
        ),
        migrations.AddField(
            model_name='conferencista',
            name='biografia',
            field=models.CharField(default='nil', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
