# Generated by Django 3.2.3 on 2021-08-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0002_auto_20210827_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='password_zoom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
