# Generated by Django 3.2.3 on 2021-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0003_conferencia_password_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='duracion',
            field=models.DurationField(),
        ),
    ]
