# Generated by Django 3.2.3 on 2021-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0004_alter_conferencia_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='password_zoom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
