# Generated by Django 3.2.6 on 2021-09-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0007_alter_conferencista_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
