# Generated by Django 3.2.6 on 2021-08-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prerregistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('comunidad', models.CharField(max_length=20)),
                ('cantidad_pagada', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'prerregistro',
            },
        ),
    ]
