# Generated by Django 3.2.3 on 2021-08-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerregistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerregistro',
            name='comunidad',
            field=models.CharField(max_length=100),
        ),
    ]
