# Generated by Django 3.2.3 on 2021-08-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prerregistro', '0003_alter_prerregistro_cantidad_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerregistro',
            name='usuario_db',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
